"""empty message

Revision ID: 8e1ca386fd82
Revises: 54da4d5f928b
Create Date: 2020-05-01 15:54:27.013457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e1ca386fd82'
down_revision = '54da4d5f928b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('users_uuid_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_uuid_key', 'users', ['uuid'])
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
