openapi: "3.0.0"
servers: []
info:
  title: Todo List API
  description: This is a documentation for rest API on the application [https://todolist.agus.website](https://todolist.agus.website) 
  version: "1.0.0"
  contact:
    name: Agus Stiawan
    url: https://agus.website
    email: agus.stiawan2211@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: user_aggregation_service
    description: Endpoints for managing user data from database
paths:
  /{user_id}:
    get:
      tags:
        - user_aggregation_service
      parameters:
      - name: user_id
        description: User ID, fill with UUID from user credentials
        in: path
        required: true
        schema:
          type: string
          format: uuid  
          $ref: "#/components/schema/Users"
      responses:
        '200':
          description: Found a user
        '404':
          description: Record not found
components:
  schemas:
    Users:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 5
          maxLength: 25
        email:
          type: string
          minLength: 3
          maxLength: 255
          format: unique
        username:
          type: string
          minLength: 5
          maxLength: 25
          format: unique
        password:
          type: string
          maxLength: 255
    ProfileImages:
      type: object
      properties:
        id:
          type: integer
          format: uint8